/* Font Face Observer v2.0.14 - © Bram Stein. License: BSD-3-Clause */(function(){'use strict';var f,g=[];function l(a){g.push(a);1==g.length&&f()}function m(){for(;g.length;)g[0](),g.shift()}f=function(){setTimeout(m)};function n(a){this.a=p;this.b=void 0;this.f=[];var b=this;try{a(function(a){q(b,a)},function(a){r(b,a)})}catch(c){r(b,c)}}var p=2;function t(a){return new n(function(b,c){c(a)})}function u(a){return new n(function(b){b(a)})}function q(a,b){if(a.a==p){if(b==a)throw new TypeError;var c=!1;try{var d=b&&b.then;if(null!=b&&"object"==typeof b&&"function"==typeof d){d.call(b,function(b){c||q(a,b);c=!0},function(b){c||r(a,b);c=!0});return}}catch(e){c||r(a,e);return}a.a=0;a.b=b;v(a)}}
function r(a,b){if(a.a==p){if(b==a)throw new TypeError;a.a=1;a.b=b;v(a)}}function v(a){l(function(){if(a.a!=p)for(;a.f.length;){var b=a.f.shift(),c=b[0],d=b[1],e=b[2],b=b[3];try{0==a.a?"function"==typeof c?e(c.call(void 0,a.b)):e(a.b):1==a.a&&("function"==typeof d?e(d.call(void 0,a.b)):b(a.b))}catch(h){b(h)}}})}n.prototype.g=function(a){return this.c(void 0,a)};n.prototype.c=function(a,b){var c=this;return new n(function(d,e){c.f.push([a,b,d,e]);v(c)})};
function w(a){return new n(function(b,c){function d(c){return function(d){h[c]=d;e+=1;e==a.length&&b(h)}}var e=0,h=[];0==a.length&&b(h);for(var k=0;k<a.length;k+=1)u(a[k]).c(d(k),c)})}function x(a){return new n(function(b,c){for(var d=0;d<a.length;d+=1)u(a[d]).c(b,c)})};window.Promise||(window.Promise=n,window.Promise.resolve=u,window.Promise.reject=t,window.Promise.race=x,window.Promise.all=w,window.Promise.prototype.then=n.prototype.c,window.Promise.prototype["catch"]=n.prototype.g);}());

(function(){function l(a){this.document=a||window.document}l.prototype.createElement=function(a){return this.document.createElement(a)};l.prototype.style=function(a,b){a.style.cssText=b};l.prototype.append=function(a,b){a.appendChild(b)};l.prototype.addListener=function(a,b,c){this.document.addEventListener?a.addEventListener(b,c,!1):a.attachEvent(b,c)};
function n(a,b){a.document.body?b():a.document.addEventListener?a.document.addEventListener("DOMContentLoaded",function k(){this.document.removeEventListener("DOMContentLoaded",k);b()}):a.document.attachEvent("onreadystatechange",function m(){if("interactive"==this.document.readyState||"complete"==this.document.readyState)this.document.detachEvent("onreadystatechange",m),b()})};function r(a,b){this.a=b;this.b=this.a.createElement("div");this.b.setAttribute("aria-hidden","true");this.a.append(this.b,this.a.document.createTextNode(a));this.c=this.a.createElement("span");this.f=this.a.createElement("span");this.i=this.a.createElement("span");this.g=this.a.createElement("span");this.h=-1;this.a.style(this.c,"max-width:none;display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;");this.a.style(this.f,"max-width:none;display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;");
this.a.style(this.g,"max-width:none;display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;");this.a.style(this.i,"display:inline-block;width:200%;height:200%;font-size:16px;max-width:none;");this.a.append(this.c,this.i);this.a.append(this.f,this.g);this.a.append(this.b,this.c);this.a.append(this.b,this.f)}
function t(a,b){a.a.style(a.b,"max-width:none;min-width:20px;min-height:20px;display:inline-block;overflow:hidden;position:absolute;width:auto;margin:0;padding:0;top:-999px;white-space:nowrap;font-synthesis:none;font:"+b+";")}function u(a){var b=a.b.offsetWidth,c=b+100;a.g.style.width=c+"px";a.f.scrollLeft=c;a.c.scrollLeft=a.c.scrollWidth+100;return a.h!==b?(a.h=b,!0):!1}
function z(a,b){function c(){var a=k;u(a)&&null!==a.b.parentNode&&b(a.h)}var k=a;a.a.addListener(a.c,"scroll",c);a.a.addListener(a.f,"scroll",c);u(a)};function A(a,b){var c=b||{};this.document=c.document||window.document;this.a=new l(this.document);this.family=a;this.style=c.style||"normal";this.weight=c.weight||"normal";this.stretch=c.stretch||"normal"}var B=null,C=null,D=null,F=null;function G(){if(null===C)if(J()&&/Apple/.test(window.navigator.vendor)){var a=/AppleWebKit\/([0-9]+)(?:\.([0-9]+))(?:\.([0-9]+))/.exec(window.navigator.userAgent);C=!!a&&603>parseInt(a[1],10)}else C=!1;return C}
function J(){null===F&&(F=!!document.fonts);return F}function K(a){if(null===D){a=a.a.createElement("div");try{a.style.font="condensed 100px sans-serif"}catch(b){}D=""!==a.style.font}return D}function L(a,b){return[a.style,a.weight,K(a)?a.stretch:"","100px",b].join(" ")}
A.prototype.load=function(a,b){var c=this,k=a||"BESbswy",m=0,E=b||3E3,H=(new Date).getTime();return new Promise(function(a,b){if(J()&&!G()){var M=new Promise(function(a,b){function e(){(new Date).getTime()-H>=E?b():c.document.fonts.load(L(c,'"'+c.family+'"'),k).then(function(c){1<=c.length?a():setTimeout(e,25)},function(){b()})}e()}),N=new Promise(function(a,c){m=setTimeout(c,E)});Promise.race([N,M]).then(function(){clearTimeout(m);a(c)},function(){b(c)})}else n(c.a,function(){function v(){var b;
if(b=-1!=f&&-1!=g||-1!=f&&-1!=h||-1!=g&&-1!=h)(b=f!=g&&f!=h&&g!=h)||(null===B&&(b=/AppleWebKit\/([0-9]+)(?:\.([0-9]+))/.exec(window.navigator.userAgent),B=!!b&&(536>parseInt(b[1],10)||536===parseInt(b[1],10)&&11>=parseInt(b[2],10))),b=B&&(f==w&&g==w&&h==w||f==x&&g==x&&h==x||f==y&&g==y&&h==y)),b=!b;b&&(d.parentNode&&d.parentNode.removeChild(d),clearTimeout(m),a(c))}function I(){if((new Date).getTime()-H>=E)d.parentNode&&d.parentNode.removeChild(d),b(c);else{var a=c.document.hidden;if(!0===a||void 0===
a)f=e.b.offsetWidth,g=p.b.offsetWidth,h=q.b.offsetWidth,v();m=setTimeout(I,50)}}var e=new r(k,c.a),p=new r(k,c.a),q=new r(k,c.a),f=-1,g=-1,h=-1,w=-1,x=-1,y=-1,d=c.a.createElement("div");d.dir="ltr";t(e,L(c,"sans-serif"));t(p,L(c,"serif"));t(q,L(c,"monospace"));c.a.append(d,e.b);c.a.append(d,p.b);c.a.append(d,q.b);c.a.append(c.document.body,d);w=e.b.offsetWidth;x=p.b.offsetWidth;y=q.b.offsetWidth;I();z(e,function(a){f=a;v()});t(e,L(c,'"'+c.family+'",sans-serif'));z(p,function(a){g=a;v()});t(p,L(c,
'"'+c.family+'",serif'));z(q,function(a){h=a;v()});t(q,L(c,'"'+c.family+'",monospace'))})})};"object"===typeof module?module.exports=A:(window.FontFaceObserver=A,window.FontFaceObserver.prototype.load=A.prototype.load);}());
